name: CI Release

on:
  workflow_run:
    workflows: ["CI Build"]
    branches: [master]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Release Fix
        if: "!contains(github.event.head_commit.message, '@RELEASE_MINOR')"
        run: echo Releasing fix!
      - name: Release Minor
        if: "contains(github.event.head_commit.message, '@RELEASE_MINOR')"
        run: echo Releasing minor!
        
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Failed
        run: echo Releas canceled!
